unique_ids:
  assets:
    standard-page.html: EJK3B7IY76XJCYYRQBS5JCHZIJCL2N5L
    theme.css: 45T7VSKMAXNKHZK52K6WTMDTN725UHTO
  forms:
    Form1: DLNN67ZSONG4RLJLTBMHD2MMSRP6IMOX
  modules: {}
  scripts: {}
  server_modules: {}
